version: "3.7"
services:
  coordinator:
    image: maxilect-coordinator
    restart: always
    networks:
      - internal
    ports:
      - "8080:8080"
    environment:
      - COORDINATOR_PORT=8080
  generator:
    image: maxilect-generator
    restart: always
    networks:
      - internal
    ports:
    - "8081-8082:8081"
    depends_on:
      - coordinator
    environment:
      - GENERATOR_PORT=8081
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - generator
      - coordinator
    ports:
      - "8084:8080"
    restart: always
    networks:
      - internal
networks:
  internal:
